/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIs;
import java.sql.*;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Vikum
 */
public class Import extends javax.swing.JFrame {

    private static Connection Connection;
    Connection con =null;
    PreparedStatement pst =null;
    PreparedStatement pst2 =null;
    ResultSet rs =null;
    ResultSet rs2 =null;
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Import
     */
    public Import() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jTable1.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));
        AutoCompleteDecorator.decorate(supplier);
        
        
        Object col[]= {"Product Code","Brand Name","Item","Qty","Price Per Item","Min Rate","MFD","EXP","Supplier","DateTime"};
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        con = Import.ConnectDB();
        updateTable();
        supplierUpdate();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        insert_panel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        item = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        MFD = new datechooser.beans.DateChooserCombo();
        EXP = new datechooser.beans.DateChooserCombo();
        jLabel16 = new javax.swing.JLabel();
        supplier = new javax.swing.JComboBox<>();
        category = new javax.swing.JTextField();
        Product_code = new javax.swing.JTextField();
        min_rate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        quantitiy = new javax.swing.JSpinner();
        brand_name = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        display_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button_panel = new javax.swing.JPanel();
        btn_reset = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btn_add = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_update = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parent.setAlignmentX(200.0F);
        parent.setMinimumSize(new java.awt.Dimension(1220, 680));
        parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insert_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Total");
        insert_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, -1, -1));

        item.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActionPerformed(evt);
            }
        });
        insert_panel.add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 210, 30));

        Total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insert_panel.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 130, -1));

        MFD.setCalendarPreferredSize(new java.awt.Dimension(290, 200));
        MFD.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 12));
        insert_panel.add(MFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        EXP.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));
        insert_panel.add(EXP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Supplier");
        insert_panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        supplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insert_panel.add(supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 210, 30));

        category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insert_panel.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 160, 30));

        Product_code.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Product_code.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        insert_panel.add(Product_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 160, 30));

        min_rate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        min_rate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        insert_panel.add(min_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 160, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("EXP");
        insert_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 120, 20));

        quantitiy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insert_panel.add(quantitiy, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 60, -1));

        brand_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insert_panel.add(brand_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 210, 30));

        price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insert_panel.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 140, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Item");
        insert_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Category");
        insert_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Product Code");
        insert_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Brand Name");
        insert_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Quantity");
        insert_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Price Per\nOne item(Rs.)");
        insert_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Min Rate");
        insert_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("MFD");
        insert_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 20));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        insert_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 230));

        jPanel1.add(insert_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 990, 230));

        display_panel.setBackground(new java.awt.Color(255, 255, 255));
        display_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Product Code", "Brand name", "Category", "Qty", "Price Per Item", "Min Rate", "MFD", "EXP", "Suppliyer", "DateTime"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(102, 0, 102));
        jScrollPane1.setViewportView(jTable1);

        display_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 970, 250));

        jPanel1.add(display_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 990, 260));

        button_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_reset.setBackground(new java.awt.Color(102, 0, 102));
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_resetMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_resetMouseReleased(evt);
            }
        });
        btn_reset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("RESET");
        btn_reset.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        button_panel.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 150, 40));

        btn_add.setBackground(new java.awt.Color(102, 0, 102));
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_addMouseReleased(evt);
            }
        });
        btn_add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADD");
        btn_add.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        button_panel.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 150, 40));

        btn_update.setBackground(new java.awt.Color(102, 0, 102));
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_updateMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_updateMouseReleased(evt);
            }
        });
        btn_update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("UPDATE");
        btn_update.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        button_panel.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 150, 40));

        btn_delete.setBackground(new java.awt.Color(102, 0, 102));
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_deleteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_deleteMouseReleased(evt);
            }
        });
        btn_delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DELETE");
        btn_delete.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        button_panel.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 150, 40));

        jPanel1.add(button_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 990, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/istockphoto-1005362660-612x612.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 585));

        parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 1050, 585));

        getContentPane().add(parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static Connection ConnectDB(){
        try{
            Class.forName("org.sqlite.JDBC");
            Connection con= DriverManager.getConnection("jdbc:sqlite:data_from.db");
            return con;
        }
        catch(Exception e){
           
           JOptionPane.showMessageDialog(null, e);
        }
        return null;
    }
    public void supplierUpdate(){
        con = Import.ConnectDB();
        if(con!= null){
           String sql2 = "SELECT * from Supplier";
           System.out.println("eeee ");
           try{
                pst2 = con.prepareStatement(sql2);
                rs2 = pst2.executeQuery();
            while (rs2.next()) {
                String name = rs2.getString("supplyName");
                supplier.addItem(name);
                  }
           }
           catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
        }
    }
    
    public void updateTable(){
        con = Import.ConnectDB();
        if(con!= null){
           String sql = "SELECT brandId,brandName,name,supplyQTY,ppi,min_rate,MFD,EXP,supplyName,supplyDate"
                   + " from brand "
                   + "inner join item on brand.itemName = item.name "
                   + "inner join Supplier on brand.supply_regNo = Supplier.Supplier_regNo ";

           try{
                
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                Object[] columnData = new Object[10];
               // System.out.println("eeajasbc");
            while (rs.next()) {
                //System.out.println("eeeee");
                 columnData[0]= rs.getInt("brandId");
                    columnData[1]= rs.getString("brandName");
                    columnData[2]= rs.getString("name");
                    columnData[3]= rs.getString("supplyQTY");
                    columnData[4]= rs.getString("ppi");
                    columnData[5]= rs.getString("min_rate");
                    columnData[6]= rs.getString("MFD");
                    columnData[7]= rs.getString("EXP");
                    columnData[8]= rs.getString("supplyName");
                    columnData[9]= rs.getString("supplyDate");
                   model.addRow(columnData);
            }
           }
           catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
            
        }
        try {   
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void btn_addMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseReleased
        resetColor(btn_add);
    }//GEN-LAST:event_btn_addMouseReleased

    private void btn_addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMousePressed
       setColor(btn_add);
       con = Import.ConnectDB();
        if(con!= null){
            String sql = "SELECT Supplier_regNo from Supplier "
            
            
            
           String sql2 = "INSERT INTO brand(brandId,brandName,itemName,supplyQTY,supplyDate,ppi,MFD,EXP,supply_regNo) VALUES(?,?,?,?,?,?,?,?,?)";
                   
           try{
                
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                Object[] columnData = new Object[10];
                System.out.println("eeajasbc");
            while (rs.next()) {
                System.out.println("eeeee");
                 columnData[0]= rs.getInt("brandId");
                    columnData[1]= rs.getString("brandName");
                    columnData[2]= rs.getString("name");
                    columnData[3]= rs.getString("supplyQTY");
                    columnData[4]= rs.getString("ppi");
                    columnData[5]= rs.getString("min_rate");
                    columnData[6]= rs.getString("MFD");
                    columnData[7]= rs.getString("EXP");
                    columnData[8]= rs.getString("supplyName");
                    columnData[9]= rs.getString("supplyDate");
                   model.addRow(columnData);
            }
           }
           catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
            
        }
        try {   
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_addMousePressed

    private void btn_updateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMousePressed
       setColor(btn_update);
    }//GEN-LAST:event_btn_updateMousePressed

    private void btn_updateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseReleased
       resetColor(btn_update);
    }//GEN-LAST:event_btn_updateMouseReleased

    private void btn_deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMousePressed
       setColor(btn_delete);
    }//GEN-LAST:event_btn_deleteMousePressed

    private void btn_deleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseReleased
       resetColor(btn_delete);
    }//GEN-LAST:event_btn_deleteMouseReleased

    private void btn_resetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMousePressed
        setColor(btn_reset);
        try{
            Product_code.setText(null);
            Total.setText(null);
            brand_name.setText(null);
            item.setText(null);
            category.setText(null);
            min_rate.setText(null);
            price.setText(null);
            EXP.setSelectedDate(null);
            MFD.setSelectedDate(null);       
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btn_resetMousePressed

    private void btn_resetMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseReleased
        resetColor(btn_reset);
    }//GEN-LAST:event_btn_resetMouseReleased

    private void itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemActionPerformed
    
    public void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,118));
    }
    
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(102,0,102));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Import().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo EXP;
    private datechooser.beans.DateChooserCombo MFD;
    private javax.swing.JTextField Product_code;
    private javax.swing.JTextField Total;
    private javax.swing.JTextField brand_name;
    private javax.swing.JPanel btn_add;
    private javax.swing.JPanel btn_delete;
    private javax.swing.JPanel btn_reset;
    private javax.swing.JPanel btn_update;
    private javax.swing.JPanel button_panel;
    private javax.swing.JTextField category;
    private javax.swing.JPanel display_panel;
    private javax.swing.JPanel insert_panel;
    private javax.swing.JTextField item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField min_rate;
    private javax.swing.JPanel parent;
    private javax.swing.JTextField price;
    private javax.swing.JSpinner quantitiy;
    private javax.swing.JComboBox<String> supplier;
    // End of variables declaration//GEN-END:variables
}
