/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIs;
import java.sql.*;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Vikum
 */
public class Import extends javax.swing.JFrame {

    private static Connection Connection;
    Connection con =null;
    PreparedStatement pst =null;
    PreparedStatement pst2 =null;
    ResultSet rs =null;
    ResultSet rs2 =null;
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Import
     */
    public Import() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jTable1.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));
        AutoCompleteDecorator.decorate(supplier);
        
        
        Object col[]= {"Product Code","Brand Name","Item","Qty","Price Per Item","Min Rate","MFD","EXP","Supplier","DateTime"};
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        con = Import.ConnectDB();
        updateTable();
        supplierUpdate();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        insert_panel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        MFD = new com.toedter.calendar.JDateChooser();
        EXP = new com.toedter.calendar.JDateChooser();
        item = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        bar_code = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        supplier = new javax.swing.JComboBox<>();
        category = new javax.swing.JTextField();
        Product_code = new javax.swing.JTextField();
        min_rate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        quantitiy = new javax.swing.JSpinner();
        brand_name = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        display_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button_panel = new javax.swing.JPanel();
        btn_reset = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parent.setAlignmentX(200.0F);
        parent.setMinimumSize(new java.awt.Dimension(1220, 680));
        parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insert_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Total");
        insert_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, -1, -1));
        insert_panel.add(MFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 110, 30));
        insert_panel.add(EXP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 110, 30));

        item.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActionPerformed(evt);
            }
        });
        insert_panel.add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 210, 30));

        Total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insert_panel.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 130, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Bar Code");
        insert_panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 20));

        bar_code.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insert_panel.add(bar_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 160, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Supplier");
        insert_panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        supplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insert_panel.add(supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 210, 30));

        category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        insert_panel.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, 30));

        Product_code.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Product_code.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        insert_panel.add(Product_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 160, 30));

        min_rate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        min_rate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        insert_panel.add(min_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 160, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("EXP");
        insert_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 120, 20));

        quantitiy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insert_panel.add(quantitiy, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 60, -1));

        brand_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insert_panel.add(brand_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 210, 30));

        price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insert_panel.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 140, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Item");
        insert_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Category");
        insert_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Product Code");
        insert_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Brand Name");
        insert_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Quantity");
        insert_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 120, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Price Per\nOne item(Rs.)");
        insert_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Min Rate");
        insert_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("MFD");
        insert_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 20));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        insert_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 230));

        jPanel1.add(insert_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 990, 230));

        display_panel.setBackground(new java.awt.Color(255, 255, 255));
        display_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Product Code", "Brand name", "Category", "Qty", "Price Per Item", "Min Rate", "MFD", "EXP", "Suppliyer", "DateTime"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(102, 0, 102));
        jScrollPane1.setViewportView(jTable1);

        display_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 970, 250));

        jPanel1.add(display_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 990, 260));

        button_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_reset.setBackground(new java.awt.Color(102, 0, 102));
        btn_reset.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setText("RESET");
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });
        button_panel.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 120, 40));

        btn_update.setBackground(new java.awt.Color(102, 0, 102));
        btn_update.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("UPDATE");
        button_panel.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 120, 40));

        btn_delete.setBackground(new java.awt.Color(102, 0, 102));
        btn_delete.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("DELETE");
        btn_delete.setMaximumSize(new java.awt.Dimension(113, 39));
        btn_delete.setMinimumSize(new java.awt.Dimension(113, 39));
        button_panel.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 120, 40));

        btn_add.setBackground(new java.awt.Color(102, 0, 102));
        btn_add.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("ADD");
        btn_add.setMaximumSize(new java.awt.Dimension(113, 39));
        btn_add.setMinimumSize(new java.awt.Dimension(113, 39));
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addMouseClicked(evt);
            }
        });
        button_panel.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 120, 40));

        jPanel1.add(button_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 990, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/istockphoto-1005362660-612x612.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 585));

        parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 1050, 585));

        getContentPane().add(parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static Connection ConnectDB(){
        try{
            Class.forName("org.sqlite.JDBC");
            Connection con= DriverManager.getConnection("jdbc:sqlite:data_from.db");
            return con;
        }
        catch(Exception e){
           
           JOptionPane.showMessageDialog(null, e);
        }
        return null;
    }
    public void supplierUpdate(){
        con = Import.ConnectDB();
        if(con!= null){
           String sql2 = "SELECT * from Supplier";
           System.out.println("eeee ");
           try{
                pst2 = con.prepareStatement(sql2);
                rs2 = pst2.executeQuery();
            while (rs2.next()) {
                String name = rs2.getString("supplyName");
                supplier.addItem(name);
                  }
           }
           catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
        }
    }
    
    public void updateTable(){
        con = Import.ConnectDB();
        if(con!= null){
           String sql = "SELECT brandId,brandName,name,supplyQTY,ppi,min_rate,MFD,EXP,supplyName,supplyDate"
                   + " from brand "
                   + "inner join item on brand.itemName = item.name "
                   + "inner join Supplier on brand.supply_regNo = Supplier.Supplier_regNo ";

           try{
                
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                Object[] columnData = new Object[10];
               // System.out.println("eeajasbc");
            while (rs.next()) {
                //System.out.println("eeeee");
                 columnData[0]= rs.getInt("brandId");
                    columnData[1]= rs.getString("brandName");
                    columnData[2]= rs.getString("name");
                    columnData[3]= rs.getString("supplyQTY");
                    columnData[4]= rs.getString("ppi");
                    columnData[5]= rs.getString("min_rate");
                    columnData[6]= rs.getString("MFD");
                    columnData[7]= rs.getString("EXP");
                    columnData[8]= rs.getString("supplyName");
                    columnData[9]= rs.getString("supplyDate");
                   model.addRow(columnData);
            }
            con.close();
           }
           catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
            
        }
        try {   
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
        public void reset(){
            try{
                Product_code.setText(null);
                bar_code.setText(null);
                category.setText(null);
                min_rate.setText(null);
                brand_name.setText(null);
                item.setText(null);
                price.setText(null);
                Total.setText(null);
                supplier.setSelectedItem(null);
                quantitiy.setValue(0);
                MFD.setDate(null);
                EXP.setDate(null);
            }catch(Exception e){
                
            }
        }
    
        public String findRegNo(String name){
        String x= null;
        con = Import.ConnectDB();
        if(con!=null){
            String sql = "SELECT Supplier_regNo from Supplier where supplyName=?";
            
            try{
               
                pst = con.prepareStatement(sql);
                pst.setString(1,(String)supplier.getSelectedItem());
                rs = pst.executeQuery();
                if(rs.next()){
                   // System.out.println(supplyName);
                    x = rs.getString("Supplier_regNo");
                    System.out.println(x);
                    
                }
            con.close();
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
        }
        
        return x;
    }
    public void updatebrand(){
        SimpleDateFormat Dformat = new SimpleDateFormat("dd-mm-yyyy"); 
        String supplyNo=findRegNo(supplier.getSelectedItem().toString());
         con = Import.ConnectDB();
        if(con!=null){
            String sql = "INSERT INTO brand(brandId,brandName,itemName,supplyQTY,supplyDate,ppi,MFD,EXP,supply_regNo) "
                    + "VALUES(?,?,?,?,DATETIME('now'),?,?,?,?)";
            
            try{
               
                pst = con.prepareStatement(sql);
                pst.setString(1,bar_code.getText());
                pst.setString(2,brand_name.getText());
                pst.setString(3,item.getText());
                pst.setInt(4,(int) quantitiy.getValue());
                int ppi = Integer.parseInt(price.getText());
                pst.setInt(5,ppi);
                pst.setString(6,Dformat.format(MFD.getDate()));
                pst.setString(7,Dformat.format(EXP.getDate()));
                pst.setString(8,supplyNo);
                pst.execute();
                JOptionPane.showMessageDialog(null, "System Updated...");
                rs.close();
                pst.close();
                con.close();
           }catch(Exception e){
                System.out.println("error");
               JOptionPane.showMessageDialog(null, e);
               
           }
        }
    }
    public void updateitem(){
        
    }
    private void itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void btn_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseClicked
        updatebrand();
        updateTable();
        reset();
    }//GEN-LAST:event_btn_addMouseClicked

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
        reset();
    }//GEN-LAST:event_btn_resetMouseClicked
    
    public void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,118));
    }
    
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(102,0,102));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Import().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser EXP;
    private com.toedter.calendar.JDateChooser MFD;
    private javax.swing.JTextField Product_code;
    private javax.swing.JTextField Total;
    private javax.swing.JTextField bar_code;
    private javax.swing.JTextField brand_name;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_update;
    private javax.swing.JPanel button_panel;
    private javax.swing.JTextField category;
    private javax.swing.JPanel display_panel;
    private javax.swing.JPanel insert_panel;
    private javax.swing.JTextField item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField min_rate;
    private javax.swing.JPanel parent;
    private javax.swing.JTextField price;
    private javax.swing.JSpinner quantitiy;
    private javax.swing.JComboBox<String> supplier;
    // End of variables declaration//GEN-END:variables
}
